CREATE TABLE price (
  PRICE_LIST BIGINT NOT NULL,
   PRODUCT_ID BIGINT,
   BRAND_ID BIGINT,
   PRIORITY BIGINT,
   START_DATE TIMESTAMP,
   END_DATE TIMESTAMP,
   CURR VARCHAR(3),
   PRICE DOUBLE,
   CONSTRAINT pk_price PRIMARY KEY (PRICE_LIST)
);